### ISSUE TITLE
Setting Rewards to Air

### ISSUE THREAD

**Issue by Bruchpilot13** [garbagemule/MobArena#266]
Hi,
is it possible to set the rewards to air? So the players get nothing in the end? Because on my server, you can do nothing with the Items you win. But in other Minigames (the maps of them are in the same world) the players have a lot of crap, which is completely useless. So I want to remove the rewards.
In the config I set down 'air' in every line. But it doesn't work. The Whole Plugin crashes after that.

Crash Report:

[22:09:23 ERROR]: Error occurred while enabling MobArena v0.96.9 (Is it up to date?)
java.lang.NullPointerException
        at com.garbagemule.MobArena.MAUtils.getArenaRewardMap(MAUtils.java:62) ~[?:?]
        at com.garbagemule.MobArena.ArenaImpl.<init>(ArenaImpl.java:154) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArena(ArenaMasterImpl.java:575) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArenasInWorld(ArenaMasterImpl.java:533) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArenas(ArenaMasterImpl.java:517) ~[?:?]
        at com.garbagemule.MobArena.ArenaMasterImpl.initialize(ArenaMasterImpl.java:236) ~[?:?]
        at com.garbagemule.MobArena.MobArena.onEnable(MobArena.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) ~[craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:350) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:389) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:439) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:375) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:342) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:319) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:275) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:175) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:424) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-1.7.2-R0.3.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]

How I wrote it in the Config:

    rewards:
      waves:
        every:
          '3': air
          '5': air
          '10': air
        after:
          '7': air
          '13': air
          '16': air

**Comment by Pyeroh** [comment]
You could remove the 'rewards' node, it's optionnal

**Comment by Bruchpilot13** [comment]
Thank You so much! It worked!

**Comment by Bruchpilot13** [comment]
Thank you so much! It worked!
