### ISSUE TITLE
Glowstone Error

### ISSUE THREAD

**Issue by seema84** [garbagemule/MobArena#267]
Error occurred while enabling MobArena v0.96.7 (Is it up to date?)
java.lang.NullPointerException
        at com.garbagemule.MobArena.ScoreboardManager.<init>(ScoreboardManager.java:26)
        at com.garbagemule.MobArena.ArenaImpl.<init>(ArenaImpl.java:173)
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArena(ArenaMasterImpl.java:575)
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArenasInWorld(ArenaMasterImpl.java:533)
        at com.garbagemule.MobArena.ArenaMasterImpl.loadArenas(ArenaMasterImpl.java:517)
        at com.garbagemule.MobArena.ArenaMasterImpl.initialize(ArenaMasterImpl.java:236)
        at com.garbagemule.MobArena.MobArena.onEnable(MobArena.java:80)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
        at net.glowstone.GlowServer.enablePlugins(GlowServer.java:726)
        at net.glowstone.GlowServer.start(GlowServer.java:477)
        at net.glowstone.GlowServer.main(GlowServer.java:106)

**Comment by PaulBGD** [comment]
Glowstone does not have scoreboards implemented yet.

**Comment by garbagemule** [comment]
In that case, simply disabling scoreboards in MobArena should do the trick.
