### ISSUE TITLE
[Error] - Could not pass event EntityDamageByEntityEvent to MobArena

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#268]
MobArena 0.96.9.1

Spigot 1.8.7 d2856ae-8f0f4ed
```
[18:36:07] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to MobArena v0.96.9.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:86) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:539) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:452) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:571) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1101) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:859) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:742) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:242) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.projectiles.CraftBlockProjectileSource cannot be cast to org.bukkit.entity.Entity
	at com.garbagemule.MobArena.ArenaListener.onEntityDamage(ArenaListener.java:692) ~[?:?]
	at com.garbagemule.MobArena.listeners.MAGlobalListener.entityDamage(MAGlobalListener.java:151) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	... 22 more
```

**Comment by garbagemule** [comment]
Fixed in the next release :)

**Comment by mibby** [comment]
Sweet. When's the next release? :o

**Comment by garbagemule** [comment]
Come on, you know better than to ask that question ;)

**Comment by mibby** [comment]
;)

**Comment by garbagemule** [comment]
That said, I could really use someone with established setups to test out some of the major changes I'm implementing - you know where to find me if you're interested :)
