### ISSUE TITLE
Doesn't run on newer builds of Spigot

### ISSUE THREAD

**Issue by conflictxinside** [garbagemule/MobArena#292]
Spigot: git-Spigot-f04e043-e56aa46 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

[13:50:12] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ma' in plugin MobArena v0.97.2-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f04e043-e56aa46]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f04e043-e56aa46]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-f04e043-e56aa46]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-f04e043-e56aa46]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at com.garbagemule.MobArena.util.inventory.InventoryManager.hasEmptyInventory(InventoryManager.java:119) ~[?:?]
	at com.garbagemule.MobArena.ArenaImpl.canJoin(ArenaImpl.java:1520) ~[?:?]
	at com.garbagemule.MobArena.commands.user.JoinCommand.execute(JoinCommand.java:45) ~[?:?]
	at com.garbagemule.MobArena.commands.CommandHandler.onCommand(CommandHandler.java:91) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f04e043-e56aa46]
	... 15 more
[13:50:13] [Async Chat Thread - #64/INFO]: event

**Comment by garbagemule** [comment]
I'm sure I already closed an issue on this specific problem...

Well, fixed in v0.97.2 (when it's out).
