### ISSUE TITLE
Update to 1.9

### ISSUE THREAD

**Issue by rErEaT** [garbagemule/MobArena#294]
Please add support for 1.9!

[12:29:35] [Server thread/INFO]: csacsa200 issued server command: /ma j
[12:29:35] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ma' in plugin MobArena v0.97.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-90839e6-1865896]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-90839e6-1865896]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-90839e6-1865896]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-90839e6-1865896]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-90839e6-1865896]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-90839e6-1865896]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-90839e6-1865896]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-90839e6-1865896]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_71]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-90839e6-1865896]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-90839e6-1865896]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-90839e6-1865896]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-90839e6-1865896]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-90839e6-1865896]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
	at com.garbagemule.MobArena.util.inventory.InventoryManager.hasEmptyInventory(InventoryManager.java:119) ~[?:?]
	at com.garbagemule.MobArena.ArenaImpl.canJoin(ArenaImpl.java:1505) ~[?:?]
	at com.garbagemule.MobArena.commands.user.JoinCommand.execute(JoinCommand.java:45) ~[?:?]
	at com.garbagemule.MobArena.commands.CommandHandler.onCommand(CommandHandler.java:91) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-90839e6-1865896]
	... 15 more

**Comment by garbagemule** [comment]
Duplicate
