### ISSUE TITLE
IllegalArgumentException: Material cannot be null

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#298]
I believe this error happened when adding a golden apple to upgrade wave using the golden apple ID. (Though might be wrong.)

```
[13:59:36] [Server thread/WARN]: [MobArena] Task #888770 for MobArena v0.97.2-SNAPSHOT generated an exception
java.lang.IllegalArgumentException: Material cannot be null
    at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.9.4.jar:git-Paper-739]
    at org.bukkit.inventory.ItemStack.setType(ItemStack.java:173) ~[patched_1.9.4.jar:git-Paper-739]
    at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftItemStack.<init>(CraftItemStack.java:109) ~[patched_1.9.4.jar:git-Paper-739]
    at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftItemStack.<init>(CraftItemStack.java:116) ~[patched_1.9.4.jar:git-Paper-739]
    at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftItemStack.<init>(CraftItemStack.java:105) ~[patched_1.9.4.jar:git-Paper-739]
    at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftItemStack.asCraftCopy(CraftItemStack.java:84) ~[patched_1.9.4.jar:git-Paper-739]
    at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftInventory.firstPartial(CraftInventory.java:260) ~[patched_1.9.4.jar:git-Paper-739]
    at org.bukkit.craftbukkit.v1_9_R2.inventory.CraftInventory.addItem(CraftInventory.java:287) ~[patched_1.9.4.jar:git-Paper-739]
    at com.garbagemule.MobArena.ArenaClass.grantItems(ArenaClass.java:152) ~[?:?]
    at com.garbagemule.MobArena.ArenaImpl.assignClass(ArenaImpl.java:1102) ~[?:?]
    at com.garbagemule.MobArena.ArenaListener$1.run(ArenaListener.java:1100) ~[?:?]
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.4.jar:git-Paper-739]
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.4.jar:git-Paper-739]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:827) [patched_1.9.4.jar:git-Paper-739]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-739]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:728) [patched_1.9.4.jar:git-Paper-739]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627) [patched_1.9.4.jar:git-Paper-739]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

Invalid names don't error. For example;

```
[02:23:52] [Server thread/WARN]: [MobArena] Failed to parse item: GOLDENAPPLE
```

GOLDEN_APPLE does seem to work.

**Comment by aycgit** [comment]
This error looks like u left a blank spot somewhere where a item should be

**Comment by slipcor** [comment]
@mibby you did not share your config - could it be that you set the config as follows:

```all: 322```

or

```classname: 322```

Because then that is a yaml issue. You need to specify that it is a list / a string. So either use a string or surround it with single quotes :P

**Comment by garbagemule** [comment]
Reopen if this is still an issue.
