### ISSUE TITLE
Cannot join arena with empty inventory

### ISSUE THREAD

**Issue by jflory7** [garbagemule/MobArena#302]
## Problem

Today on my server, we discovered that when you set the `require-empty-inv-join` setting to `true`, the plugin will not be able to let people join an arena.
## Background Analysis

When we had this setting enabled, a player would try joining an arena and it would trigger the following stacktrace.

```
[17:02:20 INFO]: Natzic issued server command: /ma join arena
[17:02:20 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ma' in plugin MobArena v0.97.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.4.jar:git-Paper-762]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-762]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) ~[patched_1.9.4.jar:git-Paper-762]
        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-762]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-762]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-762]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-762]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-762]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-762]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-762]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-762]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-762]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-762]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at com.garbagemule.MobArena.util.inventory.InventoryManager.hasEmptyInventory(InventoryManager.java:119) ~[?:?]
        at com.garbagemule.MobArena.ArenaImpl.canJoin(ArenaImpl.java:1505) ~[?:?]
        at com.garbagemule.MobArena.commands.user.JoinCommand.execute(JoinCommand.java:45) ~[?:?]
        at com.garbagemule.MobArena.commands.CommandHandler.onCommand(CommandHandler.java:91) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.9.4.jar:git-Paper-762]
        ... 15 more
```

Setting this back to `false` instantly resolved this problem. Our full configuration file can be shared on request. Thanks @natzic for discovering this bug.

**Comment by aycgit** [comment]
Can we geta full error log and your config? I cant see anything from what u gave us

**Comment by jflory7** [comment]
@aycgit This was the full error log given when we ran into the problem. My current config can be found [here](https://paste.fedoraproject.org/392221) albeit some changes since this stacktrace. Mostly just the `require-empty-inv-join` flag.

**Comment by aycgit** [comment]
Can u give the full error from the servers logs that doesnt contain the 15 more

**Comment by garbagemule** [comment]
@jflory7 Does it happen with this build?
https://dl.dropboxusercontent.com/u/11723967/ma/MobArena.jar

**Comment by slipcor** [comment]
I have seen "AIR" contents in the standard inventory some time ago, so I would suggest pulling my version rather than just using a null check
