### ISSUE TITLE
UnsupportedOperationException: Not supported

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#324]
Caused by trying to spawn a wither_skeleton boss mob.
```
        boss4:
          priority: 6
          type: boss
          wave: 40
          name: The Hunter
          monster: wither_skeleton
          health: 600
          abilities: arrows, lightning-aura, chain-lightning
          ability-interval: 5
```

```
[14:40:35] [Server thread/WARN]: [MobArena] Task #99861 for MobArena v0.97.2-SNAPSHOT generated an exception
java.lang.UnsupportedOperationException: Not supported.
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftSkeleton.setSkeletonType(CraftSkeleton.java:36) ~[patched_1.11.jar:git-Paper-960]
	at com.garbagemule.MobArena.waves.MACreature.spawn(MACreature.java:203) ~[?:?]
	at com.garbagemule.MobArena.MASpawnThread.spawnWave(MASpawnThread.java:165) ~[?:?]
	at com.garbagemule.MobArena.MASpawnThread.run(MASpawnThread.java:117) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.jar:git-Paper-960]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.11.jar:git-Paper-960]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:807) [patched_1.11.jar:git-Paper-960]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-960]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-960]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-960]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by slipcor** [comment]
this has just been fixed :) https://dev.bukkit.org/projects/mobarena/files/2356390
