### ISSUE TITLE
EventException

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#361]
Hello. I think that i found a bug.

```
[2017-03-11 01:24:20] Could not pass event PlayerInteractEvent to MobArena v0.97.5
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[server.jar:git-Paper-1062]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-Paper-1062]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1062]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:git-Paper-1062]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-Paper-1062]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:233) ~[server.jar:git-Paper-1062]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:200) ~[server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) ~[server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) ~[server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) ~[server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.Entity.checkBlockCollisions(Entity.java:938) ~[server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:522) ~[server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:551) ~[server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) ~[server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[server.jar:git-Paper-1062]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830) [server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [server.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [server.jar:git-Paper-1062]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at com.garbagemule.MobArena.ArenaListener.onPlayerInteract(ArenaListener.java:981) ~[?:?]
	at com.garbagemule.MobArena.listeners.MAGlobalListener.playerInteract(MAGlobalListener.java:270) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor333.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[server.jar:git-Paper-1062]
	... 23 more
```

**Comment by garbagemule** [comment]
Hi. Can you explain how you found it? What were you doing when it happened? Can you reproduce it?

**Comment by molor** [comment]
@garbagemule, unfortunately, no.
It happened tonight, and this morning I saw several of these errors in the server log. So this is all I have..

**Comment by garbagemule** [comment]
What is in your lobby aside from the signs and iron block? Do you have pressure plates or trip wires or anything you can "interact" with that doesn't involve clicking?

**Comment by molor** [comment]
@garbagemule, hmm.. nothing?

![2017-03-11_13 14 04](https://cloud.githubusercontent.com/assets/19989717/23822357/bf0bbf52-065c-11e7-971b-d4ac23f336fc.png)

**Comment by garbagemule** [comment]
That's really strange. The error points to a spot in the code where it checks the "hand" of the player when the player is in the lobby and "interacts" with something (usually a click). The hand is either main hand or off hand, but shouldn't be null. Unless perhaps the interaction somehow happens without the player clicking. Or if Paper doesn't implement that bit. 

I'll try to see if I can reproduce it somehow. Thanks for the quick responses and the bug report :)

**Comment by garbagemule** [comment]
I have reproduced the issue by stepping on a pressure plate while in the lobby. The "hand" equipment slot is in fact null when interacting with stuff without clicking it.
