### ISSUE TITLE
IllegalArgumentException: A location must be at least (x,y,z)

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#390]
Messing around with the config. Need to catch this exception?

```
[07:17:32] [Server thread/ERROR]: Error occurred while enabling MobArena v0.98.1 (Is it up to date?)
java.lang.IllegalArgumentException: A location must be at least (x,y,z)
	at com.garbagemule.MobArena.util.config.ConfigUtils.parseLocation(ConfigUtils.java:80) ~[?:?]
	at com.garbagemule.MobArena.region.ArenaRegion.reloadRegion(ArenaRegion.java:69) ~[?:?]
	at com.garbagemule.MobArena.region.ArenaRegion.reloadAll(ArenaRegion.java:59) ~[?:?]
	at com.garbagemule.MobArena.region.ArenaRegion.<init>(ArenaRegion.java:51) ~[?:?]
	at com.garbagemule.MobArena.ArenaImpl.<init>(ArenaImpl.java:144) ~[?:?]
	at com.garbagemule.MobArena.ArenaMasterImpl.loadArena(ArenaMasterImpl.java:599) ~[?:?]
	at com.garbagemule.MobArena.ArenaMasterImpl.loadArenasInWorld(ArenaMasterImpl.java:557) ~[?:?]
	at com.garbagemule.MobArena.ArenaMasterImpl.loadArenas(ArenaMasterImpl.java:541) ~[?:?]
	at com.garbagemule.MobArena.ArenaMasterImpl.initialize(ArenaMasterImpl.java:240) ~[?:?]
	at com.garbagemule.MobArena.MobArena.onEnable(MobArena.java:91) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1153]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1153]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1153]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380) [patched_1.12.jar:git-Paper-1153]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1153]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [patched_1.12.jar:git-Paper-1153]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [patched_1.12.jar:git-Paper-1153]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [patched_1.12.jar:git-Paper-1153]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.jar:git-Paper-1153]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1153]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

**Comment by slipcor** [comment]
No, this is thrown on purpose ^^ it is thrown BY MobArena to make you aware of this bug :)

**Comment by garbagemule** [comment]
I assume this is resolved by now. It definitely looks like a config file mistake :)
