### ISSUE TITLE
NPE on playerdeathevent

### ISSUE THREAD

**Issue by RoboMWM** [garbagemule/MobArena#391]
Probably also need to check if msg is null.

```
[18:38:39] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to MobArena v0.98.2-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1155]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1155]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1155]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1155]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.jar:git-Paper-1155]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:449) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:972) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:766) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:603) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.Explosion.a(Explosion.java:140) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.World.createExplosion(World.java:2019) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.WorldServer.createExplosion(WorldServer.java:1243) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.EntityCreeper.dr(EntityCreeper.java:211) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.EntityCreeper.B_(EntityCreeper.java:116) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1749) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1719) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1536) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:910) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1155]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1155]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at com.garbagemule.MobArena.Messenger.tell(Messenger.java:19) ~[?:?]
	at com.garbagemule.MobArena.ArenaImpl.announce(ArenaImpl.java:433) ~[?:?]
	at com.garbagemule.MobArena.ArenaListener.onPlayerDeath(ArenaListener.java:545) ~[?:?]
	at com.garbagemule.MobArena.ArenaListener.onEntityDeath(ArenaListener.java:523) ~[?:?]
	at com.garbagemule.MobArena.listeners.MAGlobalListener.entityDeath(MAGlobalListener.java:186) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor467.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1155]
	... 23 more
```

**Comment by garbagemule** [comment]
Thanks! I'll work a fix in for next update :)

**Comment by RoboMWM** [comment]
Haven't had time to look into this thoroughly but I do know that the death message is intentionally set to null in another plugin, so I'm presuming that's probably what's happening here?

**Comment by garbagemule** [comment]
Fix will be included in next release :)
