### ISSUE TITLE
Failed to undo step SetHealth

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#480]
Paper dev 1506 (Spigot 1.12.2)
MobArena compiled as of commit https://github.com/garbagemule/MobArena/commit/5937eb0631a33aa26de10b71907eae5327b80b14

```
[19:07:24] [Server thread/ERROR]: [MobArena] Failed to undo step SetHealth(BJBGaming1)
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 23.0. (attribute base value: 20.0, player: BJBGaming1)
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:100) ~[patched_1.12.2.jar:git-Paper-1506]
	at com.garbagemule.MobArena.steps.SetHealth.undo(SetHealth.java:31) ~[?:?]
	at com.garbagemule.MobArena.steps.PlayerMultiStep.undo(PlayerMultiStep.java:58) ~[?:?]
	at com.garbagemule.MobArena.ArenaImpl.rollback(ArenaImpl.java:922) ~[?:?]
	at com.garbagemule.MobArena.ArenaImpl.discardPlayer(ArenaImpl.java:1074) ~[?:?]
	at com.garbagemule.MobArena.ArenaImpl.playerLeave(ArenaImpl.java:793) ~[?:?]
	at com.garbagemule.MobArena.commands.user.LeaveCommand.execute(LeaveCommand.java:40) ~[?:?]
	at com.garbagemule.MobArena.commands.CommandHandler.onCommand(CommandHandler.java:118) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1506]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1506]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1506]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1473) ~[patched_1.12.2.jar:git-Paper-1506]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1278) ~[patched_1.12.2.jar:git-Paper-1506]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1506]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1506]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1506]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1506]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched_1.12.2.jar:git-Paper-1506]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1506]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1506]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1506]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Comment by garbagemule** [comment]
Hey mibby, please follow the bug report issue template so we can get as much relevant information in the issue as possible from the beginning.
