### ISSUE TITLE
1.14.2 - Leaderboards broken

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#536]
# Bug report

**Short description**
When starting the arena, leaderboards sends an error.

**Reproduction steps**
1. Set up the signs, it will look like it works. "Leaderboard made. Now set up the stat signs!" "Stat sign created."
2. Join the arena, pick a class, start the arena.
3. It should now throw the error and not update the leaderboards.

**Details**
* **MobArena version**: 0.103.2
* **Server version**: Spigot 1.14.2
* **Stacktrace**: https://pastebin.com/bRjQKQba

**Additional info**
This bug was mentioned by two others in Discord this morning.

Edit: Can this bug be because 1.14 intruduced new signs? oak_sign, acacia_sign etc

**Comment by Nesseley** [comment]
Adding this here as it is kinda a same error.

Error when trying to choose class `Tester` by clicking the sign.
https://pastebin.com/eZVL4s2Y

The signs connected to a classchest works, but normal config-classes don't work.

**Comment by SaitDev** [comment]
> Adding this here as it is kinda a same error.
> 
> Error when trying to choose class `Tester` by clicking the sign.
> https://pastebin.com/eZVL4s2Y
> 
> The signs connected to a classchest works, but normal config-classes don't work.

solution https://www.spigotmc.org/threads/getting-block-behind-sign-in-1-14.370340/

**Comment by mibby** [comment]
Ah bummer, I seem to be running into this same issue. :(

```
[19:39:38] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MobArena v0.103.2
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getRelative(CraftBlock.java:250) ~[patched_1.14.3.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getRelative(CraftBlock.java:245) ~[patched_1.14.3.jar:git-Paper-132]
	at com.garbagemule.MobArena.leaderboards.Leaderboard.getSignCount(Leaderboard.java:227) ~[?:?]
	at com.garbagemule.MobArena.leaderboards.Leaderboard.isGridWellFormed(Leaderboard.java:139) ~[?:?]
	at com.garbagemule.MobArena.leaderboards.Leaderboard.initialize(Leaderboard.java:74) ~[?:?]
	at com.garbagemule.MobArena.ArenaImpl.startArena(ArenaImpl.java:555) ~[?:?]
	at com.garbagemule.MobArena.ArenaImpl.playerReady(ArenaImpl.java:751) ~[?:?]
	at com.garbagemule.MobArena.ArenaListener.handleReadyBlock(ArenaListener.java:1082) ~[?:?]
	at com.garbagemule.MobArena.ArenaListener.onPlayerInteract(ArenaListener.java:1064) ~[?:?]
	at com.garbagemule.MobArena.listeners.MAGlobalListener.playerInteract(MAGlobalListener.java:305) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1174.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-132]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-132]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-132]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.3.jar:git-Paper-132]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:445) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:443) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1398) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-132]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-132]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
