### ISSUE TITLE
Error on picking a class via sign

### ISSUE THREAD

**Issue by Nornina** [garbagemule/MobArena#553]
**Short description**
 Clicking a class sign on 1.14.4 throw the error below.

**Reproduction steps**

1. Join an arena with /ma join
2. Hit a sign to pick a class
3. Error appears in console
4. It actually is that ^

**Details**

* **MobArena version**: 0.103.2
* **Server version**: Spigot 1.14.4
* **Stacktrace** `10:26:28 AM [WARNING] [MobArena] Task #26224 for MobArena v0.103.2 generated an exception
10:26:28 AM java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
10:26:28 AM 	at com.garbagemule.MobArena.util.ClassChests.assignClassFromClassChestSearch(ClassChests.java:45) ~[?:?]
10:26:28 AM 	at com.garbagemule.MobArena.ArenaListener$1.run(ArenaListener.java:1155) ~[?:?]
10:26:28 AM 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[Paper-1.14.4-b148.jar:git-Paper-147]
10:26:28 AM 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[Paper-1.14.4-b148.jar:git-Paper-147]
10:26:28 AM 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[Paper-1.14.4-b148.jar:git-Paper-147]
10:26:28 AM 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[Paper-1.14.4-b148.jar:git-Paper-147]
10:26:28 AM 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[Paper-1.14.4-b148.jar:git-Paper-147]
10:26:29 AM 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[Paper-1.14.4-b148.jar:git-Paper-147]
10:26:29 AM 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by Nornina** [comment]
I should have checked discord to see this issue was fixed, my bad.
