### ISSUE TITLE
Error message for using 1.20.2

### ISSUE THREAD

**Issue by WayneFX** [garbagemule/MobArena#783]
Purpur 1.20.2 2092

[19:25:32 ERROR]: Could not pass event PlayerDeathEvent to MobArena v0.107                                                                                  java.util.ConcurrentModificationException: null                                                                                                                     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]                                                                                        at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]                                                                                             at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]                                                                                                      at com.garbagemule.MobArena.ArenaImpl.endArena(ArenaImpl.java:648) ~[MobArena.jar:?]                                                                        at com.garbagemule.MobArena.ArenaImpl.playerDeath(ArenaImpl.java:882) ~[MobArena.jar:?]                                                                     at com.garbagemule.MobArena.ArenaListener.onPlayerDeath(ArenaListener.java:540) ~[MobArena.jar:?]                                                           at com.garbagemule.MobArena.ArenaListener.onEntityDeath(ArenaListener.java:508) ~[MobArena.jar:?]                                                           at com.garbagemule.MobArena.listeners.MAGlobalListener.entityDeath(MAGlobalListener.java:190) ~[MobArena.jar:?]                                             at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1282.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]                                                at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2092]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2092]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2092]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:995) ~[purpur-1.20.2.jar:git-Purpur-2092]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:982) ~[?:?]                                                                                at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1596) ~[?:?]                                                                              at net.minecraft.world.entity.player.Player.hurt(Player.java:1012) ~[?:?]                                                                                   at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1162) ~[?:?]                                                                              at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:403) ~[?:?]                                                           at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:233) ~[?:?]                                                                       at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:224) ~[?:?]                                                                    at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:297) ~[?:?]                                                              at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:233) ~[?:?]                                                                  at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]                                                                                  at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1469) ~[?:?]                                                                    at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:924) ~[?:?]                                                                        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.2.jar:git-Purpur-2092]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:901) ~[?:?]                                                                                 at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1577) ~[purpur-1.20.2.jar:git-Purpur-2092]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2092]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2092]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2092]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2092]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by garbagemule** [comment]
Please use the templates.

This is not an issue with 1.20.2. Try turning off `auto-leave-on-end` and see if that helps. Feel free to reopen if the problem persists, but please use the issue template.
